[project]
name = "extend-reviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "fastapi>=0.116.1",
    "lark>=1.2.2",
    "openai>=1.102.0",
    "openpyxl>=3.1.5",
    "pytest>=8.4.1",
    "python-multipart>=0.0.20",
    "requests>=2.32.5",
    "typer[all]>=0.16.1",
    "uvicorn[standard]>=0.35.0",
]
