name: 🧙 Arcane Auditor Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build CLI + Web Executables (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform_name: Windows
            build_script: powershell .\scripts\build.ps1
            cli_artifact: dist/ArcaneAuditorCLI.exe
            web_artifact: dist/ArcaneAuditorWeb.exe
          - os: macos-latest
            platform_name: macOS
            build_script: bash ./scripts/build.sh
            cli_artifact: dist/ArcaneAuditorCLI
            web_artifact: dist/ArcaneAuditorWeb
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: 🪄 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: ⚙️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller typer click lark fastapi starlette uvicorn openpyxl python-multipart psutil

      - name: 🧰 Run build script
        run: ${{ matrix.build_script }}

      - name: 📦 Upload CLI build
        uses: actions/upload-artifact@v4
        with:
          name: ArcaneAuditor_CLI_${{ matrix.platform_name }}
          path: ${{ matrix.cli_artifact }}

      - name: 📦 Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: ArcaneAuditor_Web_${{ matrix.platform_name }}
          path: ${{ matrix.web_artifact }}