name: 🧪 Build (Unsigned Diagnostic)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            shell: pwsh
            build: ./scripts/build.ps1
          - os: macos-latest
            shell: bash
            build: ./scripts/build.sh

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧙 Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.6"

      - name: 🧩 Install pinned Python
        run: |
          echo "🕒 $(date '+%Y-%m-%d %H:%M:%S') Installing Python via uv"
          uv python install
        shell: bash

      - name: 🔍 Verify Python runtime
        run: |
          uv --version
          uv run python -V
          uv run python -c "import sys, sysconfig, platform, os; print('Python exe:', sys.executable); print('LIBDIR:', sysconfig.get_config_var('LIBDIR')); print('Platform:', platform.platform()); print('CWD:', os.getcwd())"
        shell: bash

      - name: 🏗️ Build project
        shell: ${{ matrix.shell }}
        run: |
          echo "🕒 Starting build script for ${{ runner.os }}"
          mkdir -p build-logs
          if [ "${{ runner.os }}" = "Windows" ]; then
            echo "================ BUILD START $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ================" | Tee-Object -FilePath build-logs/build_Windows.log -Append
            pwsh ${{ matrix.build }} 2>&1 | Tee-Object -FilePath build-logs/build_Windows.log -Append
            echo "================ BUILD END $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ================" | Tee-Object -FilePath build-logs/build_Windows.log -Append
          else
            echo "================ BUILD START $(date '+%Y-%m-%d %H:%M:%S') ================"
            ${{ matrix.build }} 2>&1 | tee build-logs/build_${{ runner.os }}.log
            echo "================ BUILD END $(date '+%Y-%m-%d %H:%M:%S') ================"
          fi

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arcane-auditor-${{ runner.os }}
          path: |
            dist/ArcaneAuditor*.exe
            dist/ArcaneAuditor*.app*
            dist/ArcaneAuditorCLI*
            dist/ArcaneAuditorWeb.exe
            build-logs/
