name: 🔏 Sign & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  windows-sign:
    name: 🔏 Windows EV Signing
    runs-on: self-hosted

    steps:
      - name: 📥 Download unsigned artifacts from vdevelop release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          New-Item -ItemType Directory -Force -Path ./unsigned | Out-Null
          gh release download vdevelop --repo ${{ github.repository }} --dir ./unsigned --pattern "*.exe" --clobber
          Write-Host "📦 Downloaded files:"
          Get-ChildItem ./unsigned | Format-Table Name, Length, LastWriteTime

      - name: 🔏 Sign executables (local EV cert)
        shell: pwsh
        run: |
          $thumb = "A5EBA89B65F776DB3DEB350BD3681BFF52AFE2E8"
          Get-ChildItem ./unsigned -Filter *.exe | ForEach-Object {
            Write-Host "🔏 Signing: $($_.Name)"
            & signtool sign `
              /sha1 $thumb `
              /fd sha256 `
              /td sha256 `
              /tr http://timestamp.digicert.com `
              $_.FullName
            
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to sign $($_.Name)"
              exit 1
            }
          }

      - name: 📤 Upload signed Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-windows
          path: ./unsigned/*.exe

  mac-sign-notarize:
    name: 🍎 macOS Sign + Notarize
    runs-on: macos-latest

    steps:
      - name: 🧭 Checkout repository (for helper scripts)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 📥 Download unsigned macOS artifacts from vdevelop release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./dist
          gh release download vdevelop --repo ${{ github.repository }} --dir ./dist --pattern "ArcaneAuditorCLI" --clobber
          gh release download vdevelop --repo ${{ github.repository }} --dir ./dist --pattern "ArcaneAuditor.app.zip" --clobber
          if [ -f ./dist/ArcaneAuditor.app.zip ]; then
            echo "📦 Extracting ArcaneAuditor.app with symlink preservation..."
            cd ./dist
            ditto -x -k ArcaneAuditor.app.zip .
            rm ArcaneAuditor.app.zip
            cd ..
          fi
          echo "📦 Downloaded and extracted files:"
          ls -lh ./dist/
          echo "📦 App bundle structure:"
          ls -lh ./dist/ArcaneAuditor.app/Contents/ || true

      # ✅ Restore broken framework symlink (just in case)
      - name: 🔗 Restore Python.framework symlink
        run: |
          fw_root="dist/ArcaneAuditor.app/Contents/Frameworks/Python.framework/Versions"
          if [ -d "$fw_root" ] && [ ! -L "$fw_root/Current" ]; then
            latest_ver=$(ls "$fw_root" | grep -E '^[0-9]+\.[0-9]+' | sort -V | tail -n 1 || true)
            if [ -n "$latest_ver" ]; then
              echo "🔗 Restoring Versions/Current -> $latest_ver symlink..."
              ln -sfn "$latest_ver" "$fw_root/Current"
              ls -l "$fw_root"
            else
              echo "⚠️ No version folder found under $fw_root"
            fi
          fi

      - name: 🔏 Import mac certificate
        env:
          MAC_CERT: ${{ secrets.MACOS_CERTIFICATE }}
          MAC_CERT_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: |
          echo "$MAC_CERT" | base64 --decode > cert.p12
          security create-keychain -p password build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p password build.keychain
          security import cert.p12 -k build.keychain -P "$MAC_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k password build.keychain
          rm cert.p12

      - name: 🔏 Codesign App & CLI
        env:
          MAC_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
        run: |
          echo "🔏 Signing CLI binary..."
          codesign --force --options runtime --sign "$MAC_IDENTITY" dist/ArcaneAuditorCLI --timestamp

          echo "✅ Preserving Python.framework and python3.x runtime (no flattening needed)"

          # 🧹 Ensure no stray Python.framework binaries remain in Resources
          echo "🧹 Removing stray Python.framework copies..."
          find dist/ArcaneAuditor.app/Contents/Resources -type d -name "Python.framework" -exec rm -rf {} + || true

          echo "🧩 Verifying Python.framework symlink structure..."
          ls -l dist/ArcaneAuditor.app/Contents/Frameworks/Python.framework/Versions || true

          echo "🧹 Moving non-Mach-O files from Frameworks to Resources..."
          if [ -d "dist/ArcaneAuditor.app/Contents/Frameworks" ]; then
            find dist/ArcaneAuditor.app/Contents/Frameworks -type f | while read f; do
              if ! file "$f" | grep -q "Mach-O"; then
                rel_path="${f#dist/ArcaneAuditor.app/Contents/Frameworks/}"
                target="dist/ArcaneAuditor.app/Contents/Resources/lib/$rel_path"
                mkdir -p "$(dirname "$target")"
                mv "$f" "$target"
                echo "  Moved: $rel_path"
              fi
            done
            find dist/ArcaneAuditor.app/Contents/Frameworks -type d -empty -delete 2>/dev/null || true
          fi

          echo "🔏 Signing all Mach-O binaries in app bundle..."
          find dist/ArcaneAuditor.app/Contents -type f | while read f; do
            if file "$f" | grep -q "Mach-O"; then
              echo "  Signing: $f"
              codesign --force --options runtime --sign "$MAC_IDENTITY" "$f" --timestamp 2>/dev/null || true
            fi
          done

          echo "🔏 Signing main app bundle..."
          codesign --force --deep --options runtime --sign "$MAC_IDENTITY" dist/ArcaneAuditor.app --timestamp
          codesign --verify --verbose dist/ArcaneAuditorCLI
          codesign --verify --verbose dist/ArcaneAuditor.app
          codesign -dvv dist/ArcaneAuditor.app

      - name: 🚀 Notarize App
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: ./scripts/notarize.sh dist/ArcaneAuditor.app

      - name: 📜 Upload notarization logs (App)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notarization-logs-app
          path: notary-logs/

      - name: 🚀 Notarize CLI
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: ./scripts/notarize.sh dist/ArcaneAuditorCLI
     
      - name: 📜 Upload notarization logs (CLI)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notarization-logs-cli
          path: notary-logs/

      - name: 📦 Create & Sign DMG
        run: |
          mkdir dmg
          # ✅ Preserve symlinks when copying
          cp -R -P dist/ArcaneAuditor.app dmg/
          hdiutil create -volname "Arcane Auditor" \
            -srcfolder dmg \
            -ov -format UDZO \
            dist/ArcaneAuditor_macOS_Desktop.dmg
          rm -rf dmg
          codesign --force --sign "${{ secrets.MACOS_SIGNING_IDENTITY }}" dist/ArcaneAuditor_macOS_Desktop.dmg

      - name: 🚀 Notarize DMG
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: ./scripts/notarize.sh dist/ArcaneAuditor_macOS_Desktop.dmg 

      - name: 📜 Upload notarization logs (DMG)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notarization-logs-dmg
          path: notary-logs/

      - name: 📤 Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-macos
          path: |
            dist/*.dmg
            dist/ArcaneAuditorCLI

  publish:
    name: 🚀 Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [windows-sign, mac-sign-notarize]

    steps:
      - uses: actions/checkout@v4

      - name: 📥 Download all signed artifacts
        uses: actions/download-artifact@v4
        with:
          path: signed-artifacts

      - name: 📋 List all signed artifacts
        run: |
          echo "📦 All signed artifacts:"
          ls -R ./signed-artifacts/

      - name: 🎯 Organize for release
        run: |
          mkdir -p release-files
          find ./signed-artifacts -type f \( -name "*.exe" -o -name "*.dmg" -o -name "ArcaneAuditorCLI" \) -exec cp {} ./release-files/ \;
          echo "📦 Files ready for release:"
          ls -lh ./release-files/

      - name: 🚀 Create Draft Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          draft: true
          prerelease: false
          body: "Signed release artifacts. Please add release notes before publishing."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
